{
 "title": "FSI Pattern",
 "time": { "from": "now-1h", "to": "now-5m" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "currency_pair",
    "label": "Metric's Currency Pair",
    "query": "select distinct symbol from ${PROJECT_ID}.forex.metrics"
   },
   { "name": "model_threshold", "label": "Model Threshold", "query": "72" },
   {
    "name": "model_currency_pair",
    "label": "Model's Currency Pair",
    "query": "select distinct symbol from ${PROJECT_ID}.forex.metrics"
   }
  ]
 },
 "panels": [
  {
   "title": "Live Prices of Foreign Exchange",
   "type": "table",
   "gridPos": { "h": 18, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "forex",
     "orderByCol": "1",
     "orderBySort": "2",
     "project": "${PROJECT_ID}",
     "rawSql": "SELECT timestamp, symbol, value, FROM (\n  SELECT timestamp, symbol, value, RANK() OVER (PARTITION BY symbol ORDER BY timestamp DESC) dest_rank\n  FROM ${PROJECT_ID}.forex.prices\n  ) WHERE dest_rank = 1"
    }
   ]
  },
  { "title": "Gap Filling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CADJPY - Underlying Price vs Simple Moving Average",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "forex",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "${PROJECT_ID}",
     "rawSql": "SELECT\n  time_column,\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    {
     "dataset": "forex",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "${PROJECT_ID}",
     "rawSql": "SELECT\n  time_column,\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Simple Moving Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "forex",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "${PROJECT_ID}",
     "rawSql": "SELECT\n  timestamp,\n  SIMPLE_MOVING_AVERAGE\nFROM\n  ${PROJECT_ID}.forex.metrics\nWHERE\n  $__timeFilter(timestamp)\n  AND symbol=\"$currency_pair\"\nORDER BY timestamp ASC\n"
    },
    {
     "dataset": "forex",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "${PROJECT_ID}",
     "rawSql": "SELECT\n  time_column,\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Exponential Moving Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "forex",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "${PROJECT_ID}",
     "rawSql": "SELECT\n  time_column,\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    {
     "dataset": "forex",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "${PROJECT_ID}",
     "rawSql": "SELECT\n  time_column,\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Log Returns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "forex",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "${PROJECT_ID}",
     "rawSql": "SELECT\n  time_column,\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Relative Strength Indicator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "forex",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "${PROJECT_ID}",
     "rawSql": "SELECT\n  time_column,\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Bollinger Bands (SMA)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "forex",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "${PROJECT_ID}",
     "rawSql": "SELECT\n  time_column,\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    {
     "dataset": "forex",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "${PROJECT_ID}",
     "rawSql": "SELECT\n  time_column,\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Bollinger Bands (EMA)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "forex",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "${PROJECT_ID}",
     "rawSql": "SELECT\n  time_column,\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    {
     "dataset": "forex",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "${PROJECT_ID}",
     "rawSql": "SELECT\n  time_column,\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  { "title": "Model", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "RSI Valuations vs Underlying price",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dataset": "forex",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "${PROJECT_ID}",
     "rawSql": "SELECT\n  time_column,\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    {
     "dataset": "forex",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "${PROJECT_ID}",
     "rawSql": "SELECT timestamp,\nCASE\n    WHEN RELATIVE_STRENGTH_INDICATOR > 70 THEN 1\n    ELSE 0\nEND AS OVERVALUED\nFROM ${PROJECT_ID}.forex.metrics\nWHERE $__timeFilter(timestamp)\nAND symbol = \"$model_currency_pair\"\nORDER BY timestamp ASC"
    },
    {
     "dataset": "forex",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "${PROJECT_ID}",
     "rawSql": "SELECT timestamp,\nCASE\n    WHEN RELATIVE_STRENGTH_INDICATOR < 30 THEN 1\n    ELSE 0\nEND AS UNDERVALUED\nFROM ${PROJECT_ID}.forex.metrics\nWHERE $__timeFilter(timestamp)\nAND symbol = \"$model_currency_pair\"\nORDER BY timestamp ASC"
    },
    {
     "dataset": "forex",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "${PROJECT_ID}",
     "rawSql": "SELECT timestamp,\nCASE\n    WHEN reconstruction_error > $model_threshold THEN 1\n    ELSE 0\nEND AS UNRELIABLE_RSI\nFROM ${PROJECT_ID}.forex.reconerr\nWHERE $__timeFilter(timestamp)\nAND symbol = \"$model_currency_pair\"\nORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "RSI Valuations vs Simple Moving Average",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dataset": "forex",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "${PROJECT_ID}",
     "rawSql": "SELECT\n  time_column,\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    {
     "dataset": "forex",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "${PROJECT_ID}",
     "rawSql": "SELECT timestamp,\nCASE\n    WHEN RELATIVE_STRENGTH_INDICATOR > 70 THEN 1\n    ELSE 0\nEND AS OVERVALUED\nFROM ${PROJECT_ID}.forex.metrics\nWHERE $__timeFilter(timestamp)\nAND symbol = \"$model_currency_pair\"\nORDER BY timestamp ASC"
    },
    {
     "dataset": "forex",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "${PROJECT_ID}",
     "rawSql": "SELECT timestamp,\nCASE\n    WHEN RELATIVE_STRENGTH_INDICATOR < 30 THEN 1\n    ELSE 0\nEND AS UNDERVALUED\nFROM ${PROJECT_ID}.forex.metrics\nWHERE $__timeFilter(timestamp)\nAND symbol = \"$model_currency_pair\"\nORDER BY timestamp ASC"
    },
    {
     "dataset": "forex",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "${PROJECT_ID}",
     "rawSql": "SELECT timestamp,\nCASE\n    WHEN reconstruction_error > $model_threshold THEN 1\n    ELSE 0\nEND AS UNRELIABLE_RSI\nFROM ${PROJECT_ID}.forex.reconerr\nWHERE $__timeFilter(timestamp)\nAND symbol = \"$model_currency_pair\"\nORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "RSI Valuations vs Exponential Moving Average",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dataset": "forex",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "${PROJECT_ID}",
     "rawSql": "SELECT\n  time_column,\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    {
     "dataset": "forex",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "${PROJECT_ID}",
     "rawSql": "SELECT timestamp,\nCASE\n    WHEN RELATIVE_STRENGTH_INDICATOR > 70 THEN 1\n    ELSE 0\nEND AS OVERVALUED\nFROM ${PROJECT_ID}.forex.metrics\nWHERE $__timeFilter(timestamp)\nAND symbol = \"$model_currency_pair\"\nORDER BY timestamp ASC"
    },
    {
     "dataset": "forex",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "${PROJECT_ID}",
     "rawSql": "SELECT timestamp,\nCASE\n    WHEN RELATIVE_STRENGTH_INDICATOR < 30 THEN 1\n    ELSE 0\nEND AS UNDERVALUED\nFROM ${PROJECT_ID}.forex.metrics\nWHERE $__timeFilter(timestamp)\nAND symbol = \"$model_currency_pair\"\nORDER BY timestamp ASC"
    },
    {
     "dataset": "forex",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "${PROJECT_ID}",
     "rawSql": "SELECT timestamp,\nCASE\n    WHEN reconstruction_error > $model_threshold THEN 1\n    ELSE 0\nEND AS UNRELIABLE_RSI\nFROM ${PROJECT_ID}.forex.reconerr\nWHERE $__timeFilter(timestamp)\nAND symbol = \"$model_currency_pair\"\nORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "RSI Valuations vs Log Returns",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dataset": "forex",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "${PROJECT_ID}",
     "rawSql": "SELECT\n  time_column,\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    {
     "dataset": "forex",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "${PROJECT_ID}",
     "rawSql": "SELECT timestamp,\nCASE\n    WHEN RELATIVE_STRENGTH_INDICATOR > 70 THEN 1\n    ELSE 0\nEND AS OVERVALUED\nFROM ${PROJECT_ID}.forex.metrics\nWHERE $__timeFilter(timestamp)\nAND symbol = \"$model_currency_pair\"\nORDER BY timestamp ASC"
    },
    {
     "dataset": "forex",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "${PROJECT_ID}",
     "rawSql": "SELECT timestamp,\nCASE\n    WHEN RELATIVE_STRENGTH_INDICATOR < 30 THEN 1\n    ELSE 0\nEND AS UNDERVALUED\nFROM ${PROJECT_ID}.forex.metrics\nWHERE $__timeFilter(timestamp)\nAND symbol = \"$model_currency_pair\"\nORDER BY timestamp ASC"
    },
    {
     "dataset": "forex",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "${PROJECT_ID}",
     "rawSql": "SELECT timestamp,\nCASE\n    WHEN reconstruction_error > $model_threshold THEN 1\n    ELSE 0\nEND AS UNRELIABLE_RSI\nFROM ${PROJECT_ID}.forex.reconerr\nWHERE $__timeFilter(timestamp)\nAND symbol = \"$model_currency_pair\"\nORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "RSI Valuations vs Standard Deviation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dataset": "forex",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "${PROJECT_ID}",
     "rawSql": "SELECT\n  time_column,\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    {
     "dataset": "forex",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "${PROJECT_ID}",
     "rawSql": "SELECT timestamp,\nCASE\n    WHEN RELATIVE_STRENGTH_INDICATOR > 70 THEN 1\n    ELSE 0\nEND AS OVERVALUED\nFROM ${PROJECT_ID}.forex.metrics\nWHERE $__timeFilter(timestamp)\nAND symbol = \"$model_currency_pair\"\nORDER BY timestamp ASC"
    },
    {
     "dataset": "forex",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "${PROJECT_ID}",
     "rawSql": "SELECT timestamp,\nCASE\n    WHEN RELATIVE_STRENGTH_INDICATOR < 30 THEN 1\n    ELSE 0\nEND AS UNDERVALUED\nFROM ${PROJECT_ID}.forex.metrics\nWHERE $__timeFilter(timestamp)\nAND symbol = \"$model_currency_pair\"\nORDER BY timestamp ASC"
    },
    {
     "dataset": "forex",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "${PROJECT_ID}",
     "rawSql": "SELECT timestamp,\nCASE\n    WHEN reconstruction_error > $model_threshold THEN 1\n    ELSE 0\nEND AS UNRELIABLE_RSI\nFROM ${PROJECT_ID}.forex.reconerr\nWHERE $__timeFilter(timestamp)\nAND symbol = \"$model_currency_pair\"\nORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "RSI Valuations vs Relative Strength Indicator",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dataset": "forex",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "${PROJECT_ID}",
     "rawSql": "SELECT\n  time_column,\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    {
     "dataset": "forex",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "${PROJECT_ID}",
     "rawSql": "SELECT timestamp,\nCASE\n    WHEN RELATIVE_STRENGTH_INDICATOR > 70 THEN 1\n    ELSE 0\nEND AS OVERVALUED\nFROM ${PROJECT_ID}.forex.metrics\nWHERE $__timeFilter(timestamp)\nAND symbol = \"$model_currency_pair\"\nORDER BY timestamp ASC"
    },
    {
     "dataset": "forex",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "${PROJECT_ID}",
     "rawSql": "SELECT timestamp,\nCASE\n    WHEN RELATIVE_STRENGTH_INDICATOR < 30 THEN 1\n    ELSE 0\nEND AS UNDERVALUED\nFROM ${PROJECT_ID}.forex.metrics\nWHERE $__timeFilter(timestamp)\nAND symbol = \"$model_currency_pair\"\nORDER BY timestamp ASC"
    },
    {
     "dataset": "forex",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "${PROJECT_ID}",
     "rawSql": "SELECT timestamp,\nCASE\n    WHEN reconstruction_error > $model_threshold THEN 1\n    ELSE 0\nEND AS UNRELIABLE_RSI\nFROM ${PROJECT_ID}.forex.reconerr\nWHERE $__timeFilter(timestamp)\nAND symbol = \"$model_currency_pair\"\nORDER BY timestamp ASC"
    }
   ]
  }
 ]
}